-- CREAR NUEVO USUARIO (SCHEMA)
CREATE USER ETL_USER IDENTIFIED BY 1235;
CREATE USER PARAMETROS IDENTIFIED BY 1235;

-- ASIGNAR PERMISO DE ADMINISTRADOR A LOS SCHEMAS
GRANT DBA TO ETL_USER;
GRANT DBA TO PARAMETROS;


-- CREAR TABLA DE PARÁMETROS DE CONEXIÓN
CREATE TABLE PARAMETROS.PARAMETROS (
    SISTEMA         VARCHAR2 (100 CHAR),
    NOMBRE_PARAM    VARCHAR2 (100 CHAR),
    VALOR_PARAM     VARCHAR2 (100 CHAR)
);

-- INSERTAR VARIABLES DE CONEXIÓN
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) VALUES ('PROYECTO_PENTAHO','HOSTNAME','localhost');
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) VALUES ('PROYECTO_PENTAHO','DATABASENAME','orcl');
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) VALUES ('PROYECTO_PENTAHO','PORTNUMBER','1521');
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) VALUES ('PROYECTO_PENTAHO','USERNAME','ETL_USER');
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) VALUES ('PROYECTO_PENTAHO','SCHEMA','ODS');
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) VALUES ('PROYECTO_PENTAHO','DIR_FILE', 'C:\WAITS\PROYECTO\');
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) VALUES ('PROYECTO_PENTAHO','PASSWORD','1235');
INSERT INTO PARAMETROS.PARAMETROS (SISTEMA, NOMBRE_PARAM, VALOR_PARAM) VALUES ('PROYECTO_PENTAHO','SCHEMA_DW', 'DATA_WAREHOUSE');
COMMIT;

-- CONSULTA DE DATOS
SELECT * FROM PARAMETROS.PARAMETROS;

-- ELIMINAR TABLA
DROP TABLE PARAMETROS.PARAMETROS;

-- TRUNCAR TABLA
TRUNCATE TABLE PARAMETROS.PARAMETROS;